spring:
  application:
    name: msavaliadorcredito
  rabbitmq:
    rost: ${RABBITMQ_SERVER:localhost}
    port: 5672
    username: guest
    password: guest

server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://user:1234@${EUREKA_SERVER:localhost}:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: ${AVALIADOR_HOST:localhost}
mq:
  queues:
    emissao-cartoes: emissao-cartoes
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  file:
    name: ./log/log-file.log

